-- Classroom Board V17.1 backend
-- Run once in Supabase SQL Editor for the project used by Kathleens magische Kiste.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.classroom_sessions (
  id uuid primary key default gen_random_uuid(),
  room_code text not null unique,
  teacher_token uuid not null default gen_random_uuid(),
  title text not null default 'Unterricht',
  class_name text,
  status text not null default 'open',
  phase text not null default 'free',
  traffic text not null default 'green',
  frozen boolean not null default false,
  board_state jsonb not null default '{}'::jsonb,
  viewport jsonb not null default '{"scale":0.65,"tx":-500,"ty":-350}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.classroom_participants (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.classroom_sessions(id) on delete cascade,
  student_token uuid not null default gen_random_uuid(),
  device_token text not null,
  display_name text not null,
  state text not null default 'working',
  can_write boolean not null default false,
  locked boolean not null default false,
  follow_teacher boolean not null default true,
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(session_id, student_token)
);

create table if not exists public.classroom_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.classroom_sessions(id) on delete cascade,
  participant_id uuid references public.classroom_participants(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.classroom_student_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.classroom_sessions(id) on delete cascade,
  participant_id uuid not null references public.classroom_participants(id) on delete cascade,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.classroom_sessions enable row level security;
alter table public.classroom_participants enable row level security;
alter table public.classroom_messages enable row level security;
alter table public.classroom_student_events enable row level security;

create or replace function public.classroom_random_code()
returns text language plpgsql volatile as $$
declare c text;
begin
  loop
    c := upper(substr(encode(extensions.gen_random_bytes(8),'hex'),1,6));
    exit when not exists(select 1 from public.classroom_sessions where room_code=c and status='open');
  end loop;
  return c;
end $$;

create or replace function public.classroom_create(p_passphrase text, p_title text default 'Unterricht', p_class_name text default null)
returns jsonb language plpgsql security definer set search_path=public,extensions,pg_catalog as $$
declare s public.classroom_sessions;
begin
  if not public.toolbox_verify_admin(p_passphrase) then
    raise exception 'Admin-Passwort falsch';
  end if;
  insert into public.classroom_sessions(room_code,title,class_name)
  values(public.classroom_random_code(),coalesce(nullif(p_title,''),'Unterricht'),p_class_name)
  returning * into s;
  return jsonb_build_object('session_id',s.id,'teacher_token',s.teacher_token,'room_code',s.room_code);
end $$;

create or replace function public.classroom_teacher_sync(p_session uuid,p_teacher_token uuid,p_board_state jsonb,p_viewport jsonb)
returns boolean language plpgsql security definer set search_path=public,pg_catalog as $$
begin
  update public.classroom_sessions
  set board_state=coalesce(p_board_state,'{}'::jsonb),viewport=coalesce(p_viewport,viewport),updated_at=now()
  where id=p_session and teacher_token=p_teacher_token and status='open';
  return found;
end $$;

create or replace function public.classroom_join(p_room_code text,p_display_name text,p_device_token text)
returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$
declare s public.classroom_sessions; p public.classroom_participants;
begin
  select * into s from public.classroom_sessions where room_code=upper(trim(p_room_code)) and status='open' order by created_at desc limit 1;
  if s.id is null then return jsonb_build_object('ok',false,'error','room_not_found'); end if;
  select * into p from public.classroom_participants where session_id=s.id and lower(display_name)=lower(trim(p_display_name)) order by created_at desc limit 1;
  if p.id is not null and p.device_token<>p_device_token and p.last_seen>now()-interval '2 minutes' then
    return jsonb_build_object('ok',false,'error','name_in_use');
  end if;
  if p.id is null then
    insert into public.classroom_participants(session_id,device_token,display_name)
    values(s.id,p_device_token,trim(p_display_name)) returning * into p;
  else
    update public.classroom_participants set device_token=p_device_token,last_seen=now() where id=p.id returning * into p;
  end if;
  return jsonb_build_object('ok',true,'student_token',p.student_token,'room_code',s.room_code);
end $$;

create or replace function public.classroom_student_state(p_student_token uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$
declare p public.classroom_participants; s public.classroom_sessions; msgs jsonb;
begin
  select * into p from public.classroom_participants where student_token=p_student_token limit 1;
  if p.id is null then return jsonb_build_object('ok',false); end if;
  update public.classroom_participants set last_seen=now() where id=p.id;
  select * into s from public.classroom_sessions where id=p.session_id;
  select coalesce(jsonb_agg(jsonb_build_object('id',m.id,'body',m.body,'created_at',m.created_at) order by m.id),'[]'::jsonb) into msgs
  from public.classroom_messages m where m.session_id=s.id and (m.participant_id is null or m.participant_id=p.id) and m.created_at>now()-interval '30 minutes';
  return jsonb_build_object('ok',true,'session_state',case when s.status='open' then 'open' else 'closed' end,'phase',s.phase,'traffic',s.traffic,'locked',p.locked,'can_write',p.can_write,'follow_teacher',p.follow_teacher,'board_state',s.board_state,'viewport',s.viewport,'messages',msgs);
end $$;

create or replace function public.classroom_student_update(p_student_token uuid,p_state text)
returns boolean language plpgsql security definer set search_path=public,pg_catalog as $$
begin
  update public.classroom_participants set state=coalesce(nullif(p_state,''),state),last_seen=now() where student_token=p_student_token;
  return found;
end $$;

create or replace function public.classroom_student_board_event(p_student_token uuid,p_payload jsonb)
returns boolean language plpgsql security definer set search_path=public,pg_catalog as $$
declare p public.classroom_participants;
begin
  select * into p from public.classroom_participants where student_token=p_student_token limit 1;
  if p.id is null or not p.can_write then return false; end if;
  insert into public.classroom_student_events(session_id,participant_id,payload) values(p.session_id,p.id,p_payload);
  update public.classroom_participants set last_seen=now() where id=p.id;
  return true;
end $$;

create or replace function public.classroom_presentation_state(p_room_code text)
returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$
declare s public.classroom_sessions;
begin
  select * into s from public.classroom_sessions where room_code=upper(trim(p_room_code)) order by created_at desc limit 1;
  if s.id is null then return jsonb_build_object('ok',false); end if;
  return jsonb_build_object('ok',true,'phase',s.phase,'traffic',s.traffic,'frozen',s.frozen,'board_state',s.board_state,'viewport',s.viewport,'session_state',case when s.status='open' then 'open' else 'closed' end);
end $$;

create or replace function public.classroom_teacher_state(p_session uuid,p_teacher_token uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$
declare s public.classroom_sessions; ps jsonb;
begin
  select * into s from public.classroom_sessions where id=p_session and teacher_token=p_teacher_token;
  if s.id is null then return jsonb_build_object('ok',false); end if;
  select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'name',p.display_name,'state',p.state,'can_write',p.can_write,'locked',p.locked,'follow_teacher',p.follow_teacher,'online',p.last_seen>now()-interval '15 seconds') order by p.display_name),'[]'::jsonb) into ps
  from public.classroom_participants p where p.session_id=s.id;
  return jsonb_build_object('ok',true,'room_code',s.room_code,'title',s.title,'class_name',s.class_name,'phase',s.phase,'traffic',s.traffic,'frozen',s.frozen,'participants',ps);
end $$;

create or replace function public.classroom_teacher_command(p_session uuid,p_teacher_token uuid,p_command text,p_participant uuid default null,p_value jsonb default '{}'::jsonb)
returns boolean language plpgsql security definer set search_path=public,pg_catalog as $$
begin
  if not exists(select 1 from public.classroom_sessions where id=p_session and teacher_token=p_teacher_token) then return false; end if;
  case p_command
    when 'lock_all' then update public.classroom_participants set locked=true where session_id=p_session;
    when 'unlock_all' then update public.classroom_participants set locked=false where session_id=p_session;
    when 'follow_all' then update public.classroom_participants set follow_teacher=coalesce((p_value->>'enabled')::boolean,true) where session_id=p_session;
    when 'class_write' then update public.classroom_participants set can_write=coalesce((p_value->>'enabled')::boolean,false) where session_id=p_session;
    when 'lock_one' then update public.classroom_participants set locked=true where id=p_participant and session_id=p_session;
    when 'unlock_one' then update public.classroom_participants set locked=false where id=p_participant and session_id=p_session;
    when 'write_one' then update public.classroom_participants set can_write=coalesce((p_value->>'enabled')::boolean,false) where id=p_participant and session_id=p_session;
    when 'message' then insert into public.classroom_messages(session_id,participant_id,body) values(p_session,p_participant,coalesce(p_value->>'body',''));
    when 'phase' then update public.classroom_sessions set phase=coalesce(p_value->>'phase',phase),updated_at=now() where id=p_session;
    when 'traffic' then update public.classroom_sessions set traffic=coalesce(p_value->>'traffic',traffic),updated_at=now() where id=p_session;
    when 'freeze' then update public.classroom_sessions set frozen=coalesce((p_value->>'enabled')::boolean,false),updated_at=now() where id=p_session;
    when 'close' then update public.classroom_sessions set status='closed',updated_at=now() where id=p_session;
    else return false;
  end case;
  return true;
end $$;

grant execute on function public.classroom_create(text,text,text) to anon, authenticated;
grant execute on function public.classroom_teacher_sync(uuid,uuid,jsonb,jsonb) to anon, authenticated;
grant execute on function public.classroom_join(text,text,text) to anon, authenticated;
grant execute on function public.classroom_student_state(uuid) to anon, authenticated;
grant execute on function public.classroom_student_update(uuid,text) to anon, authenticated;
grant execute on function public.classroom_student_board_event(uuid,jsonb) to anon, authenticated;
grant execute on function public.classroom_presentation_state(text) to anon, authenticated;
grant execute on function public.classroom_teacher_state(uuid,uuid) to anon, authenticated;
grant execute on function public.classroom_teacher_command(uuid,uuid,text,uuid,jsonb) to anon, authenticated;
